export const  AUTH_SUCCESS ='AUTH_SUCCESS'
export const LOG_OUT ='LOG_OUT'

 export const FETCH_EVENTS_START = 'FETCH_EVENTS_START'
 export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
 export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL'

 export const CREATE_EVENT_SUCCESS ='CREATE_EVENT_SUCCESS'
 export const CREATE_EVENT_FAIL ='CREATE_EVENT_FAIL'

  export const FETCH_BOOKINGS_START = 'FETCH_BOOKINGS_START'
 export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS'
 export const FETCH_BOOKINGS_FAIL = 'FETCH_BOOKINGS_FAIL'
 